CREATE DATABASE NORTHSTAR;

CREATE WAREHOUSE NS_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

CREATE OR REPLACE SCHEMA NS_SCHEMA;


CREATE OR REPLACE DATABASE TASTY_BYTES;

CREATE OR REPLACE SCHEMA TASTY_BYTES.RAW_POS;

CREATE OR REPLACE STAGE TASTY_BYTES.PUBLIC.S3LOAD
URL = 's3://sfquickstarts/tasty-bytes-builder-education/';

CREATE OR REPLACE TABLE TASTY_BYTES.RAW_POS.country(
   country_id NUMBER(18,0),
   country VARCHAR(16777216),
   iso_currency VARCHAR(3),
   iso_country VARCHAR(2),
   city_id NUMBER(19,0),
   city VARCHAR(16777216),
   city_population VARCHAR(16777216)
);

CREATE OR REPLACE FILE FORMAT TASTY_BYTES.PUBLIC.CSV_FF;

file_format = tasty_bytes.public.csv_ff;

COPY INTO tasty_bytes.raw_pos.country
FROM @tasty_bytes.public.s3load/raw_pos/country/;